version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: cooperativa_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cooperativa
      MYSQL_USER: cooperativa_user
      MYSQL_PASSWORD: cooperativa_pass
    ports:
      - "3307:3306"
    command: [
      "--default_authentication_plugin=mysql_native_password",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    ]
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/cooperativa.sql:/docker-entrypoint-initdb.d/cooperativa.sql:ro,z

  php-api:
    build: ./src
    container_name: cooperativa_api
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html:Z
    depends_on:
      - mysql

  frontend:
    image: httpd:2.4
    container_name: cooperativa_frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src/frontend:/usr/local/apache2/htdocs/:Z

volumes:
  db_data:
